### ISSUE TITLE
Documentation example for multiple deployments in one chart

### ISSUE THREAD

**Issue by abh** [bjw-s/helm-charts#100]
My app has multiple independent deployments. They have separate readiness, scheduling, etc; but need to be deployed with the same image.

It'd be great to have an example of how to use the new common chart and do extra "custom" deployments sharing the base templates and configurations. In my case the deployments are all the same except the command and args.

Ideally each deployment would also have a headless service to target with a ServiceMonitor.

Is this possible to do with the new common chart, or would I be better off making separate charts and having a meta chart with the others as a dependency?

**Comment by onedr0p** [comment]
Here's one example

https://github.com/immich-app/immich-charts

**Comment by abh** [comment]
Thanks @onedr0p. In that example the lib/ directory (and more) seems to be either copied between each deployment/service verbatim (okay if so, I guess) or copied and modified slightly (less manageable than separate charts, IMO). Is that right?

**Comment by abh** [comment]
Very cool. Thank you, @bjw-s.

**Comment by bjw-s** [comment]
Provided in the upcoming beta of common lib 2
