### ISSUE TITLE
Knative Service Controller Type

### ISSUE THREAD

**Issue by gabe565** [bjw-s/helm-charts#103]
# Details

**Describe the solution you'd like:**

I have recently started migrating some less used deployments to Knative, which can scale to 0 until an ingress request occurs.

To deploy these "serverless" containers, Knative uses its own Service CRD which is basically a combination of a standard Deployment, Service, and Ingress. They have a good example and comparison at [Converting a Kubernetes Deployment to a Knative Service](https://knative.dev/docs/serving/convert-deployment-to-knative-service/).

I would like to implement a new controller type for for this, but want to check first to see if there's any sort of desire for this and if a PR would be accepted. Knative obviously doesn't ship with Kubernetes so I don't want to confuse users of the common library.

**Anything else you would like to add:**

It would be nice if the common library could create a Knative service with a new controller type called something like `knative-service`.

This may be complicated to implement since it would affect how services and ingresses are created, but it has been frustrating to completely scrap Helm when I migrate a site.

**Additional Information:**

I really enjoy using the common library chart. Thank you for everything that you do!

**Comment by bjw-s** [comment]
Hi! Thanks for reaching out!
Currently I am not really looking to add (m)any non-native resource types. I am however looking into adding the ability to add "arbitrary" resources through the common lib/app template soon. Maybe that could be enough to help your use case?

**Comment by gabe565** [comment]
Completely understood.

The main thing I'm aiming for is being able to swap controller types painlessly. The recent addition of CronJob controllers has allowed me to change my backups from Deployments to CronJobs with minimal changes to values.yaml, and I'd like to be able to do that when moving things to Knative. I think arbitrary resources could work, but it would depend on how configurable they are. In this case, a service does not need to be created because Knative creates it automagically.

I may look into building a library chart for Knative that uses your common library chart, and selectively calls the necessary templates in `bjw-s.common.loader.generate`. I'll see how doable that is!

Thank you!
