### ISSUE TITLE
Add finalizers to meta data

### ISSUE THREAD

**Issue by AWendland-CryptoCompare** [bjw-s/helm-charts#116]
# Details

**Describe the solution you'd like:**

An additional field that would allow you to add Finalizers to resources.

**Anything else you would like to add:**

Sorry if you can already do this and I have missed it!
I am happy to make a PR to try and do it but would be good to know where you think it would be best to go.

**Comment by bjw-s** [comment]
Hi! Thanks for raising this issue. I am curious what your use case would be for manually adding finalizers to resources?

**Comment by AWendland-CryptoCompare** [comment]
Hi Bᴇʀɴᴅ, so my initial use case doesn't apply (due to my lack of understanding). I use argocd and was finding when I deleted applications running helmcharts built using this library that some of the deployments were not dying. Though this can be corrected by using a finalizer on the application level rather than the resources of the chart.

Therefore you can close the issue. The only other use-case I could think of was in the case of a cronjob but that is really me trying to save face than anything else!

**Comment by bjw-s** [comment]
Thanks for reporting back 😃 Also happy to hear you are finding value in app-template / my common library. I'll go ahead and close the issue, but feel free to reopen if you think of another use case 👍🏻
