### ISSUE TITLE
app-template doesn't like the image tag in the form a.b

### ISSUE THREAD

**Issue by szinn** [bjw-s/helm-charts#128]
# Details

Required to put quotes around the tag since it wasn't in the form a.b.c

https://github.com/szinn/k8s-homelab/commit/9c998ed556712c87d1b9b01a2873f0c7bbbf12cc

**What did you expect to happen:**

I would expect a tag to work without quotes. Is it a semver comparison issue?

**Comment by onedr0p** [comment]
This is actually an issue with YAML spec and YAML parsers. I think it might be possible to force this to be a quoted value in the template though for the main container at least.

**Comment by szinn** [comment]
Good to know

**Comment by bjw-s** [comment]
Hi! Apologies for the delay in response... Devin is right in that it is an issue with YAML parsers automagically trying to convert that format into an integer. I'll be sure to add a `| quote` in there

**Comment by bjw-s** [comment]
Should be fixed with the upcoming common lib version, thanks again for reporting! 👍
