### ISSUE TITLE
Allow service loadbalancer modifier

### ISSUE THREAD

**Issue by zaggash** [bjw-s/helm-charts#138]
# Details

**Describe the solution you'd like:**

With the Kubernetes version 1.24 you can add the service config  like below:

`spec.allocateLoadBalancerNodePorts: false/true`

This allows the LB service to not create NodePort when the LB service is created.
The feature is now stable.

**Anything else you would like to add:**

Would it be possible to enable this option to be enabled when creating a LoadBalancer service Type.  

https://kubernetes.io/docs/concepts/services-networking/service/#load-balancer-nodeport-allocation

**Comment by bjw-s** [comment]
Hi! Thanks for the feature request! I will add this to the rewrite that I am working on. Unfortunately time has not been on my side so progress has been a bit slower than I'd hoped.

**Comment by bjw-s** [comment]
Implemented in upcoming common lib version
