### ISSUE TITLE
Multiple Images

### ISSUE THREAD

**Issue by TheDarkula** [bjw-s/helm-charts#159]
First off, thank you for the template, it works brilliantly.

I have written a number of values files successfully for services that are a single microservice (no external database).

In the [examples](https://github.com/bjw-s/helm-charts/tree/main/examples), I did not see anything that uses more than one image, nor did I see a way to use multiple in the provided [values](https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml) file.

How would I create something like a web service with a postgresql database?

**Comment by bjw-s** [comment]
In the current version of app-template it's not possible to run multiple Pods. It is however possible to run multiple containers in the same Pod, so depending on what your end goal is, you should look in to the `sidecars` key: <https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml#L213>. Just as an FYI, this behavior will change in an upcoming version.

**Comment by TheDarkula** [comment]
I am thinking of something simple like translating a docker-compose file that has two services, say, one web frontend, and one database.
Would the sidecars implementation be the best/correct way to accomplish this with the current template? If so, is there an example of it being used somewhere?

Also, what will the behaviour be in the new version?

**Comment by onedr0p** [comment]
I'm not sure if that was just an example but if not you should never put an app container and it's database container in the same pod.

**Comment by TheDarkula** [comment]
I think I see the mechanic to use with the template.
As opposed to an all-in-one values file, I need to create multiple, one for each service.

**Comment by bjw-s** [comment]
The changes in the upcoming beta of common lib 2 should cover this.
