### ISSUE TITLE
UDP/TCP Ingress

### ISSUE THREAD

**Issue by TheDarkula** [bjw-s/helm-charts#166]
I am not sure if this is covered anywhere, but is there a way to have the `ingress` block create an [IngressRouteUDP](https://doc.traefik.io/traefik/routing/providers/kubernetes-crd/#kind-ingressrouteudp)/[IngressRouteTCP](https://doc.traefik.io/traefik/routing/providers/kubernetes-crd/#kind-ingressroutetcp) for traefik?

**Comment by bjw-s** [comment]
Howdy! Thabk you for reaching out! No, app-template and/or the common library don't support Traefik CRD's. Currently there are also no plans to add that support.
