### ISSUE TITLE
Add default container securityContext

### ISSUE THREAD

**Issue by JJGadgets** [bjw-s/helm-charts#204]
# Details

**Describe the solution you'd like:**

Since there is a `defaultPodOptions.securityContext` in app-template v2.0, it would be nice to have a `defaultContainerSecurityContext` or similar so that a standardized securityContext can be applied to all containers in a HelmRelease using app-template.

This would be helpful for e.g. meeting `restricted` pod-security policy.

**Comment by JJGadgets** [comment]
As noted in Discord: more consideration and discussion would be needed, for factors such as *how* global should this be scoped (e.g. all containers in all controllers, all containers in a given controller, etc).

**Comment by onedr0p** [comment]
A possible solution could be what I recommended in https://github.com/bjw-s/helm-charts/issues/254#issuecomment-2057012021 ?

**Comment by bjw-s** [comment]
I guess I could also do something like `controllers.x.defaultContainerOptions`? But should those options also apply to initContainers?

**Comment by onedr0p** [comment]
Maybe we can include an option `controllers.x.defaultContainerOptions.applyToInitContainers=true/false` ?
