### ISSUE TITLE
Docs: Remove inaccurate info

### ISSUE THREAD

**Issue by GwynHannay** [bjw-s/helm-charts#205]
# Details

The documentation for upgrading app-template from 1xx to 2xx contains an inaccurate dot point when explaining changes:

![Screenshot 2023-10-09 at 10 39 28](https://github.com/bjw-s/helm-charts/assets/8345824/b6f2b066-f458-47b2-88a9-dc452fc6d0e8)

The sentence says 

> `ingress.main.enabled` can be removed, since items are considered enabled by default (they can still be disabled by adding `enabled: false`). 

This is incorrect as the app-template still has `enabled: false` as the default, so anyone removing that line from their values would have their ingress removed.

This line is found on this page:
https://bjw-s.github.io/helm-charts/docs/app-template/#from-1xx-to-20x

Please let me know if you require any further details or if I can help in any way. :-)

**Comment by bjw-s** [comment]
Thanks for the heads-up! I'll update the docs on this. In general the remark is correct as Ingress items will default to being enabled, but for the `main` one that's not the case due to the "overridden" value in values.yaml. This is something I plan to remedy in an upcoming v3 bump.

**Comment by GwynHannay** [comment]
Ah, I get you - I noticed the same thing with the default "config" persistence item, but then I saw that your example in the docs was for a persistence item called "media" and kind of realised that any other persistence item was correctly "true" by default.

Exciting stuff, thanks! :-)
