### ISSUE TITLE
Remove (comment) default objects

### ISSUE THREAD

**Issue by bjw-s** [bjw-s/helm-charts#206]
# Details

**Describe the solution you'd like:**

As a remnant from the old KaH library a number of objects are present in the `values.yaml` by default so that `helm-docs` would generate the value descriptions in the README:
- A `controllers.main.containers.main` container / controller
- A `service.main` Service
- A `ingress.main` Ingress
- A `persistence.config` item
- And perhaps some other stuff as well

These should be removed and put in some form of documentation instead:
- values.yaml comments
- JSON schema
- Site docs

**Anything else you would like to add:**

Current thinking is to put this in a JSON schema and potentially have this render into the README

**Relates to:**

- #123 
- #205

**Comment by gclawes** [comment]
Is the idea to remove the built-in `main` objects so we don't have to set `controllers.main.enabled=false` if we want to use other names besides `main`?

**Comment by samip5** [comment]
My issue is probably related to this, so I'm adding this as comment here. If I disable the main controller, it seems that it exposes a few suboptimal default statements which would need some fixing.

```
 Warning  error   26s   helm-controller  Helm install failed: template: app-template/templates/common.yaml:14:3: executing "app-template/templates/common.yaml" at <include "bjw-s.common.loader.generate" .>: error calling include: template: app-template/charts/common/templates/loader/_generate.tpl:8:6: executing "bjw-s.common.loader.generate" at <include "bjw-s.common.render.controllers" .>: error calling include: template: app-template/charts/common/templates/render/_controllers.tpl:37:12: executing "bjw-s.common.render.controllers" at <include "bjw-s.common.class.statefulset" (dict "rootContext" $ "object" $statefulsetObject)>: error calling include: template: app-template/charts/common/templates/classes/_statefulset.tpl:32:67: executing "bjw-s.common.class.statefulset" at <$statefulsetObject.statefulset.podManagementPolicy>: nil pointer evaluating interface {}.podManagementPolicy
 ```
Source: https://github.com/samip5/k8s-cluster/blob/6c189bfdb5343ef0c8114deded92c661148078f0/k8s/nebula/apps/default/immich/app/hr.yaml

https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/templates/classes/_statefulset.tpl#L32
