### ISSUE TITLE
FR: More advanced examples, eg Home-Assistant with Code container and ingress for both

### ISSUE THREAD

**Issue by samip5** [bjw-s/helm-charts#212]
# Details

I'm quite frustrated when the addons were removed (in 2.x of app-template), but no example shows how one would then convert the addon so I can have ingress into it as well.

**Describe the solution you'd like:**

I would like more advanced examples, particularly for Home Assistant with Code server.

**Anything else you would like to add:**

It really pains me when I'm trying to look though the code to find anything.

**Comment by remkolems** [comment]
@samip5 Do you know [https://kubesearch.dev](https://kubesearch.dev)? 

Take a look for example at the excellent resources:

- https://kubesearch.dev/hr/ghcr.io-bjw-s-helm-app-template-home-assistant-code#hr
- [onedr0p/home-ops](https://github.com/onedr0p/home-ops)
- [bjw-s/home-ops](https://github.com/bjw-s/home-ops)

Most likely others within k8s-at-home community have already done exactly that.

**Comment by remkolems** [comment]
To be honest this has bitten me as well. Chart version 2.0.3 template was a surprise to say the least.

Isn't there a tool (DevSecOps way: CI/CD) that preemptively alerts you or even converts x% from the original yaml file from previous (v1.5.3) to the latest (v2.0.3) chart template?

Renovatebot updated to v2.0.3 from v1.5.3 without me realizing clearly enough that a large part of many many many app yaml files had to be converted as well.

**Comment by samip5** [comment]
> @samip5 Do you know [https://kubesearch.dev](https://kubesearch.dev)? Search query: `home-assistant-code`


I do know it and I did search with it but wasn't able to find any that used the new way to do add-ons with ingress but I was able to do it with helm from @JJGadgets's on Discord.

**Comment by bjw-s** [comment]
> Renovatebot updated to v2.0.3 from v1.5.3 without me realizing clearly enough that a large part of many many many app yaml files had to be converted as well.

To be fair, having Renovate automatically(?) merge a change which indicates a breaking change without going over the release notes is typically not the best approach 😅

> I would like more advanced examples, particularly for Home Assistant with Code server.

Each example I add is another thing I need to maintain and try and keep up to date, otherwise it'll be raining issues about my examples not working. As this is mostly a one-person project that I can only dedicate a a certain amount of time on outside my other activities and responsibilities, I'd rather focus my efforts on improving/expanding the actual features. Glad you got it sorted lit though!

> It really pains me when I'm trying to look though the code to find anything.

Not really sure what this is supposed to add to the issue? It comes across to me as a bit hostile and Infeel that's unwarranted. While I can understand some frustration, please keep what I said above in mind :(

**Comment by samip5** [comment]
> Not really sure what this is supposed to add to the issue? It comes across to me as a bit hostile and Infeel that's unwarranted. While I can understand some frustration, please keep what I said above in mind :(

Sorry if that's the way it came across, but that wasn't how I meant it. I sincerely fail to find really anything when I'm trying to just look at the source instead of an example which unfortunately does frustrate me.

Maybe some docs on the layout would be useful? I think one of the issues is that I'm not sure when to look into e.g. render templates and when to the other folders.

**Comment by remkolems** [comment]
> > Renovatebot updated to v2.0.3 from v1.5.3 without me realizing clearly enough that a large part of many many many app yaml files had to be converted as well.
> 
> To be fair, having Renovate automatically(?) merge a change which indicates a breaking change without going over the release notes is typically not the best approach 😅

You've made my day. It's even worse: manually approved/merged. Wasn't awake and clear headed or something. 😨 -> It was a very good lesson learned though. Big thumbs up to GitOps / IaC!

Thanks for all the hard work! Without you and k8s-at-home ... I could not have done this.
