### ISSUE TITLE
Support for `defaultBackend` for ingresses

### ISSUE THREAD

**Issue by invakid404** [bjw-s/helm-charts#215]
# Details

Currently, there's no way to set the `defaultBackend` for an ingress. The `app-template` chart seems to only understand how to define `rules`, and setting `defaultBackend` does nothing.

For some use cases (e.g. when [using the tailscale-operator](https://tailscale.com/kb/1236/kubernetes-operator/#ingress-resource)), one might want to use `defaultBackend` as opposed to defining `rules`. It would be useful if `app-template` supported it.

**Additional Information:**

N/A

**Comment by bjw-s** [comment]
Thanks for raising the issue. I've added this functionality to v2.1.0
