### ISSUE TITLE
Ability to specify `.spec.timeZone` in `CronJob`

### ISSUE THREAD

**Issue by onedr0p** [bjw-s/helm-charts#218]
# Details

**Describe the solution you'd like:**

It would be awesome to have the ability to set the timezone on a cronjob:

https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/#time-zones

**Comment by bjw-s** [comment]
This would require the `kubeVersion` to jump to 1.27 though if I'm not mistaking?

**Comment by onedr0p** [comment]
That or a kube version check on the individual field?

**Comment by bjw-s** [comment]
> That or a kube version check on the individual field?

Doh... It was still early when I replied this morning I guess :D

**Comment by bjw-s** [comment]
Added support in upcoming v2.1.0
