### ISSUE TITLE
Bump required `kubeVersion` in `Chart.yaml`

### ISSUE THREAD

**Issue by onedr0p** [bjw-s/helm-charts#219]
# Details

**Describe the solution you'd like:**

Currently this is set to `1.22.0`, and as of creating this issue I believe we should bump this to `1.25.0`

**Comment by bjw-s** [comment]
I'm not sure why we currently need to change it though? The features provided by the chart are compatible with v1.22 onward. Although I guess for v3 we can drop some versions, that wouldn't hurt.
