### ISSUE TITLE
common: envFrom is not templated so unable to target secret created by secrets: {} as its '{{ .Release.Name }}-secret'

### ISSUE THREAD

**Issue by halkeye** [bjw-s/helm-charts#253]
# Details

**What steps did you take and what happened:**

Used common/app-templates and created secrets via secrets: mechanism and trying to target it

![image](https://github.com/bjw-s/helm-charts/assets/110087/c1749c3e-97d2-4631-927c-6b3e8859dc01)

**What did you expect to happen:**

Field is templated

**Anything else you would like to add:**

**Additional Information:**

Worked around it by creating a bunch of env: that reference the secret, but can't wildcard it.

**Comment by bjw-s** [comment]
Thanks for reporting! I'll try and add something to 2.5.0 to improve the `envFrom` behavior
