### ISSUE TITLE
Add env to defaultPodOptions

### ISSUE THREAD

**Issue by halkeye** [bjw-s/helm-charts#254]
# Details

**What steps did you take and what happened:**

Trying to port immich-chart to the new v2 common (awesome library btw), but running into a snag trying to reproduce the [global env](https://github.com/immich-app/immich-charts/blob/main/charts/immich/values.yaml#L7) on every pod.

**What did you expect to happen:**

Not sure, something

**Anything else you would like to add:**

**Additional Information:**

**Comment by onedr0p** [comment]
I wonder if it would be worth it to create a `defaultContainersOptions` instead and place it there or all containers in a Pod?

**Comment by halkeye** [comment]
I don't know really. I decided to not try to make a public immich chart, so havn't really used the default options much. just a bunch of copy and pasting.

**Comment by robgordon89** [comment]
i dont think this solves the issue, i believe the issue the OP is having is setting global env's on all pods/containers in all controllers etc.
