### ISSUE TITLE
mountPropagation for Volume Mounts

### ISSUE THREAD

**Issue by kiliantyler** [bjw-s/helm-charts#255]
# Details

**Describe the solution you'd like:**

Currently there is no (that I could find) way of marking VolumeMounts with `mountPropagation`

**Anything else you would like to add:**

This seems like it used to be in the chart but maybe was not ported to v2
https://github.com/k8s-at-home/library-charts/pull/76/commits/e31eeceb959b2ccf2654be87211f583f96ba4c17

**Comment by bjw-s** [comment]
Thanks for raising the issue! I've re-added the feature in the upcoming 2.5.0 release.
