### ISSUE TITLE
Mount configMap and secret by values object name

### ISSUE THREAD

**Issue by JuniorJPDJ** [bjw-s/helm-charts#281]
# Details

**Describe the solution you'd like:**
I'd like to be able to mount ConfigMap in `persistance` section using it's name from `configMaps` section.
The best would be if `secret`s would also be supported here in the same way.

**Additional Information:**
This is already possible in `envFrom` section of `controller`, this is exactly what I'd like to see in `persistance` section.

**Comment by bjw-s** [comment]
That's a great idea, thanks! :) I've added it to the upcoming v3 version

**Comment by JuniorJPDJ** [comment]
Tests on the merge request failed ;D
Thank you for very fast response and the implementation!
