### ISSUE TITLE
Support secrets for servicemonitor in app-template

### ISSUE THREAD

**Issue by runningman84** [bjw-s/helm-charts#300]
# Details

**Describe the solution you'd like:**

I would like to set these options for the serviceMonitor object:

BasicAuth
bearerTokenFile
bearerTokenSecret

**Anything else you would like to add:**

This allows us to access things like the homeassistant api which needs a bearerTokenFile for auth.

**Additional Information:**

**Comment by bjw-s** [comment]
Hi! Sorry it took me a while to get back to you on this. I was just starting work to try and implement this, but as far as I am able to tell from the docs, these fields are not supported on the serviceMonitor resource? (https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#basicauth)

**Comment by runningman84** [comment]
hmm how did the old chart work in that case?
https://github.com/k8s-at-home/charts/blob/master/charts/stable/home-assistant/templates/servicemonitor.yaml

**Comment by bjw-s** [comment]
Ooohhh, it's on the endpoints... I was looking in the wrong place. I'll take a look at adding back support for this 👍
