### ISSUE TITLE
Issue with imagePullSecrets after upgrading to version 3.X

### ISSUE THREAD

**Issue by egeback** [bjw-s/helm-charts#302]
First of all big thanks with the common chart!
# Details
I am using the app-template chart for one of my private projects. The image for this is in a private docker hub project so need to use the imagePullSecrets property in the container config.

The imagePullSecrets property works in the 2.x template versions but upgrading from 2.6.0 to 3.0.4 gives an error.

Helm values:

controllers:
  main:
    containers:
      main:
        env:
          TZ: Europe/Stockholm
        image:
          imagePullSecrets:
            - name: dockerhub-image-pull-secret
          repository: {image}//removed
          tag: v1.0.3
-------

command:
helm upgrade --history-max=5 --install=true --namespace=prod --timeout=10m0s --values=/home/shell/helm/values-app-template-3.0.4.yaml --version=3.0.4 --wait=true home-proxy /home/shell/helm/app-template-3.0.4.tgz

Error:
2024-03-16T19:24:53.102001161+01:00 Error: UPGRADE FAILED: values don't meet the specifications of the schema(s) in the following chart(s):
2024-03-16T19:24:53.102019886+01:00 app-template:
2024-03-16T19:24:53.102024624+01:00 - controllers.main.containers.main.image: Additional property imagePullSecrets is not allowed

Is imagePullSecrets still supported? Should the the imagePullSecrets be moved as part of the changes in to version 3.X?

Best Regards, Marky

**Comment by bjw-s** [comment]
Hi, thanks for raising the issue! In app-template / my common library `imagePullSecrets` are (and have been since V2 iirc) specified on the pod level, they should be set by `defaultOptions.imagePullSecrets` or something like the following if you don't want to "globally" set them:

```yaml
controllers:
  main:
    pod:
      imagePullSecrets: []
```

**Comment by egeback** [comment]
Hi

Thanks both of the options works for my use case so I could update today.
