### ISSUE TITLE
Cannot use 0 (zero) for `revisionHistoryLimit`

### ISSUE THREAD

**Issue by dangmai** [bjw-s/helm-charts#308]
# Details

**What steps did you take and what happened:**

With `app-template 3.0.4`, if you try to set `revisionHistoryLimit` to 0 in a controller, the generated manifest will actually use the default value (3), probably due to this bug: https://github.com/helm/helm/issues/3164

**What did you expect to happen:**

I'd expect `revisionHistoryLimit` in the generated manifest to be correctly set to 0.

There might be other places that use the `default` function that has this issue inside the code base, I haven't really tried looking for them yet. My use case just happens to use the `revisionHistoryLimit` property.

**Anything else you would like to add:**

**Additional Information:**

**Comment by bjw-s** [comment]
👋🏻 Thank you for raising this issue. Something similar was brought to my attention on Discord last week, and a (partial) fix has been implemented in the upcoming 3.1.0 version. I'll try and give it a broader check to see if I can find other places where this behavior could occur.
