### ISSUE TITLE
Add support for list of pure resources

### ISSUE THREAD

**Issue by via-justa** [bjw-s/helm-charts#314]
# Details

**Describe the solution you'd like:**
I love this Helm chart and use it to deploy almost all of my applications.
As I am more on the power user side, I use custom resources (some developed by me and some from upstream, like OnePasswordItem) and would love the ability to deploy them alongside the other resources.

The easiest solution for deploying unknown custom resource by the chart is to add an `otherResources` section that accepts a list of K8s API objects that the chart renders as-is. 

**Anything else you would like to add:**

**Additional Information:**

**Comment by onedr0p** [comment]
Adding this could ease the burden of supporting any unsupported resource like the linked issues above.

**Comment by via-justa** [comment]
@onedr0p or @bjw-s, would you mind elaborating on [this comment](https://github.com/bjw-s/helm-charts/issues/56#issuecomment-1298990507)?
What do you mean by saying 
```
Resources not supported by the library chart should be deployed as sidecar manifests
```
Deploying chart dependencies outside the chart is Helm's antipattern, and the developers discourage it. Or do you mean something else?
