### ISSUE TITLE
Add activeDeadlineSeconds to job and cronjob

### ISSUE THREAD

**Issue by alexyao2015** [bjw-s/helm-charts#323]
# Details

**Describe the solution you'd like:**

I would like a way to restrict the runtime of a job/cronjob. This can be done using spec.activeDeadlineSeconds, but it seems like this isn't supported today.

**Anything else you would like to add:**

**Additional Information:**

**Comment by bjw-s** [comment]
Thanks for the feature request :) I've added this to 3.2.0.
