### ISSUE TITLE
Generate schemas for HelmRelease v2

### ISSUE THREAD

**Issue by onedr0p** [bjw-s/helm-charts#324]
# Details

**Describe the solution you'd like:**

Flux bumped the HelmRelease from v2beta2 to v2

**Comment by bjw-s** [comment]
Added through https://github.com/bjw-s/helm-charts/commit/6cbaa61a4f80d2196a757156eb315fdd456302c2

Schema is available at https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
