### ISSUE TITLE
Networkpolicies not working in v3

### ISSUE THREAD

**Issue by xlemassacre** [bjw-s/helm-charts#325]
# Details

**What steps did you take and what happened:**
In Version 2 it was possible to define multiple networkpolicies via a map, after upgrading to the v3 chart there is now only one networkpolicy created.

**What did you expect to happen:**
a networkpolicy per map entry should be created

**Anything else you would like to add:**
The networkpolicy is created without the suffix.

**Comment by bjw-s** [comment]
Thanks for pointing this out! I've added a fix to 3.2.0

**Comment by xlemassacre** [comment]
Find some time now to test it, it's working again!
Thanks for the quick fix, and for this great helm chart :-)
