### ISSUE TITLE
Cannot set pod options in individual pods, only in defaultPodOptions

### ISSUE THREAD

**Issue by acuntex** [bjw-s/helm-charts#332]
# Details

**What steps did you take and what happened:**

Certain pod options like `imagePullSecrets`, `affinity`, `topologySpreadConstraints` etc. cannot be set under individual pods.
They can only be set in the `defaultPodOptions`.
If you set them under the pod, you get the error message:
```
Error: values don't meet the specifications of the schema(s) in the following chart(s):
app-template:
- controllers.pod: Additional property imagePullSecrets is not allowed
- controllers.pod: Additional property affinity is not allowed
- controllers.pod: Additional property topologySpreadConstraints is not allowed
```

Since there are test, that tests the override of these options,  I guess it was intended to work, but somehow the validation does not work as intended.
https://github.com/bjw-s/helm-charts/blob/20ca6c5003f6ef9302d3659bdfc6ef55cb955730/charts/library/common-test/tests/pod/field_topologySpreadConstraints_test.yaml#L43

**What did you expect to happen:**

Pod options like `imagePullSecrets`, `affinity`, `topologySpreadConstraints` etc. should not throw a validation error if they are used under an individual pod.

**Anything else you would like to add:**

**Additional Information:**

**Comment by bjw-s** [comment]
`controllers.pod.affinity` is not a valid option as the values validation indicates. What you are (probably) looking for is something like this:

```yaml
controllers:
  my_controller: # <-- this can be any key that you wish to use as the identifier for your controller
    pod:
      affinity:
        ...
```

Let me know if that doesn't work for you

**Comment by acuntex** [comment]
Shame on me, I was assuming the object "my_controller" was the pod-object type.
Thanks!
