### ISSUE TITLE
[Resolved] Temporary downtime due to repository shuffle

### ISSUE THREAD

**Issue by bjw-s** [bjw-s/helm-charts#355]
Just a quick FYI announcement, I am in the process of shuffling some of my repo's around on GitHub between my personal account and my organization.

For some reason GitHub doesn't allow me to transfer some of my repositories (this one is among those), so I've had to file a support ticket for that. 

Unfortunately this means that there is going to be some "downtime" (as URLs won't resolve) on my Helm charts and container images until I am allowed to transfer the repositories to the organisation :(

**Comment by bernd-schorgers** [comment]
As a temporary workaround you can point any references from `bjw-s` to `bernd-schorgers`, and that should solve any issues until I can complete the repository move. 

The downside of this is that this will probably break things again when the repo transfer is completed

**Comment by NunoSav** [comment]
https://bernd-schorgers.github.io/helm-charts redirects to https://bjw-s.github.io/helm-charts :(

**Comment by bernd-schorgers** [comment]
> https://bernd-schorgers.github.io/helm-charts redirects to https://bjw-s.github.io/helm-charts :(

That sucks :( Unfortunately there is nothing I can do about that right now until GH support gets back to me (I filed the ticket 5 hours ago, but no response yet)

**Comment by rwaltr** [comment]
Thank you for everything you do!

**Comment by leewardbound** [comment]
deep appreciations for your hard work and this fantastic project - this downtime broke 3 production CI pipelines, caused alerts from 6 clusters, and inspired me to sponsor your github. this project saves so much time, i'm happy to deal with these disturbances, please keep up the great work!

as an aside, i've had several conversations with clients and partners lately around "who is bjw-s and can we trust this project" (i'm always with the Yays but sometimes the Nays have valid concerns) - i'd love to see this repo extracted to a dedicated organization with an official name, it would encourage collaborators, add extra credibility and improve distribution!

**Comment by bjw-s** [comment]
Well... I have given up on the move to a GitHub organization (called `bjw-s`) for now. GitHub support did not respond to my ticket at all, even after almost 24 hours and what I was able to find online about GH Support response times did not provide any hope for a quick resolution.

So I have renamed my user account back to `bjw-s` which should make everything work again as it did before yesterday. Once again my apologies for this mess. I figured I had everything planned out properly to do this with as little downtime as possible, but GitHub repo protections threw a spanner in the works there.

I will try to come up with a new plan where I can somehow keep things working side by side (at least for a while).

Again, my apologies for the inconvenience!

**Comment by halkeye** [comment]
If you wanted you could probably apply for an open source account at Digital ocean (wink wink) and store everything on spaces (aka s3), then you'd have full control on the domain and stuff. Decouple it from github's urls.

**Comment by halkeye** [comment]
actually wait, a CNAME in the repo would work too

**Comment by bjw-s** [comment]
> If you wanted you could probably apply for an open source account at Digital ocean (wink wink) and store everything on spaces (aka s3), then you'd have full control on the domain and stuff. Decouple it from github's urls.

That's definitely a good idea, that would solve the issue for the "regular" Helm chart repo. I'd still need to come up with something for the GHCR OCI images. Definitely something to think about 🤔

**Comment by halkeye** [comment]
> That's definitely a good idea, that would solve the issue for the "regular" Helm chart repo. I'd still need to come up with something for the GHCR OCI images. Definitely something to think about

they have a container registry too

**Comment by bjw-s** [comment]
Oh sweet! I'll give it a better look then, thanks!

**Comment by dlahn** [comment]
Echoing @leewardbound, we strongly support the idea of transitioning this to a more official organization/repository. Expanding the number of maintainers and collaborators would be a valuable step forward, and it would also help us with our internal compliance efforts.

Please don’t hesitate to reach out if there’s anything we can do to assist in making this transition smoother. We would really like to assist with this.
