### ISSUE TITLE
Upgrade to 3.5.0, ServiceAccount reverts back to `default`

### ISSUE THREAD

**Issue by dmfrey** [bjw-s/helm-charts#359]
# Details

**What steps did you take and what happened:**
After upgrading HelmRelease to 3.5.0 for `amd-gpu-node-labeler` with a pre-defined RBAC configuration (ClusterRole, ClusterRoleBinding, and ServiceAccount), the `serviceAccount` configuration did not seem to be honored which caused the pods in the Daemonset to use the Default ServiceAccount instead of the custom defined one which has the correct permissions to read the node.

```
    serviceAccount:
      create: false
      name: amd-gpu-node-labeller
```

**What did you expect to happen:**

The Pods should use the defined service account

**Anything else you would like to add:**

Reverting the app-template to 3.4.0 fixes the issue.

**Additional Information:**

**Comment by bjw-s** [comment]
We've happened to identify this issue earlier today on Discord. @LarryGF has taken it upon himself to push a fix PR ❤️ 3.5.1 should be rolling out soon afterwards
