### ISSUE TITLE
Allow to mount configmaps

### ISSUE THREAD

**Issue by MGlants** [bjw-s/helm-charts#86]
# Details
For example i use blocky dns which gathers it configuration from data/config.yaml
I can write new configmap from chart, but i can't mount it as some path

**Comment by onedr0p** [comment]
See here for an example:

https://github.com/bjw-s/home-ops/blob/d0e9d8a8655596e0684f980824d9eab62abdab71/kubernetes/clusters/cluster-0/network/k8s-gateway/helmrelease.yaml#L30-L79

**Comment by bjw-s** [comment]
This is covered in the docs here: https://bjw-s.github.io/helm-charts/docs/common-library/common-library-storage/#configmap

**Comment by MGlants** [comment]
thank you, missed that part
