### ISSUE TITLE
.Values.secret creates envFrom in container but not Secret object

### ISSUE THREAD

**Issue by gclawes** [bjw-s/helm-charts#94]
# Details

**What steps did you take and what happened:**

Deploying an app with `.Values.secret` sets sets an `envFrom` field in the `bjw-s.common.lib.controller.mainContainer` with the release name as the secret name, but does not create a `Secret` object.

Given that `.Values.secret` does not appear in the main `values.yaml` file, it seems like this is a holdover from `k8s-at-home/common` chart.  It looks like `.Values.secrets` is supposed to replace this functionality.

**What did you expect to happen:**

Either a `Secret` object is created when `.Values.secret` is populated, or the `envFrom:` field is removed entirely.

**Anything else you would like to add:**

N/A

**Additional Information:**

N/A

**Comment by bjw-s** [comment]
That's a good find, thanks! That should have been removed when the chart migrated towards `.values.secrets`. Will fix this in an upcoming version.
